CLASSES=\
	jwsmv.Constants	\
	jwsmv.http.AbstractConnection	\
	jwsmv.http.HttpSocketConnection	\
	jwsmv.http.NtlmHttpURLConnection	\
	jwsmv.Message	\
	jwsmv.Shell	\
	jwsmv.ShellCommand	\
	jwsmv.util.Base64	\
	jwsmv.util.RFC822	\
	jwsmv.util.Xpress	\
	jwsmv.winrs.Client	\
	jwsmv.wsman.FaultException	\
	jwsmv.wsman.operation.BaseOperation	\
	jwsmv.wsman.operation.CommandOperation	\
	jwsmv.wsman.operation.CreateOperation	\
	jwsmv.wsman.operation.DeleteOperation	\
	jwsmv.wsman.operation.EnumerateOperation	\
	jwsmv.wsman.operation.GetOperation	\
	jwsmv.wsman.operation.IOperation	\
	jwsmv.wsman.operation.PullOperation	\
	jwsmv.wsman.operation.PutOperation	\
	jwsmv.wsman.operation.ReceiveOperation	\
	jwsmv.wsman.operation.ReleaseOperation	\
	jwsmv.wsman.operation.SendOperation	\
	jwsmv.wsman.operation.SignalOperation	\
	jwsmv.wsman.operation.SubscribeOperation	\
	jwsmv.wsman.operation.UnsubscribeOperation	\
	jwsmv.wsman.Port
